version: "3.1"

services:

  data:
    image: gregnuj/mariadb-galera-swarm
    environment:
      - MYSQL_DATABASE=my-stack-name
      - MYSQL_USER=my-stack-name
      - MYSQL_PASSWORD_FILE=/run/secrets/my-stack-name
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/my-stack-name-root
    secrets:
      - source: my-stack-name
        mode: 0444
      - source: my-stack-name-root
        mode: 0444
    networks:
      - internal
    volumes:
      - data-dv:/var/lib/mysql
    deploy:
      mode: global

volumes:
  data-dv:

networks:
  my-stack-name:
    driver: overlay

secrets:
  my-stack-name:
    external: true
  my-stack-name-root:
    external: true
